### ISSUE TITLE
"breaking things is easy" is broken

### ISSUE THREAD

**Issue by edoarad** [yenchenlin/awesome-adversarial-machine-learning#3]
The link for the above named blog post is broken. 
I googled and got this: http://www.cleverhans.io/security/privacy/ml/2016/12/15/breaking-things-is-easy.html

**Comment by montimonte** [comment]
Still broken

**Comment by yenchenlin** [comment]
@edoarad @montimonte seems like it's working now!

**Comment by Abhishek7081** [comment]
http://www.cleverhans.io/security/privacy/ml/2016/12/16/breaking-things-is-easy.html
